apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
spec:  
  tls:
    secretName: tls-secret
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            securityContext: {}