apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: augoor-user
spec:
  tags:
  - monitoring # other available tags are 'management' and 'administrator'
  rabbitmqClusterReference:
    name: rabbitmq-cluster
